install.versions('base64enc', '0.1-3')
install.versions('digest', '0.6.15')
install.versions('httr', '1.3.1')
install.versions('openxlsx', '4.1.0')
install.versions('R.utils', '2.7.0')
install.versions('reshape', '0.8.8')
install.versions('urltools', '1.7.0')
install.versions('xml2', '1.2.0')
install.versions('ini', '0.3.1')

