# Original analytical team packages
install.versions('argparse','2.0.0')
install.versions('testthat','2.0.0')
install.versions('data.table','1.10.4-3')
install.versions('DBI','1.0.0')
install.versions('doParallel','1.0.11')
install.versions('dplyr','0.7.4')
install.versions('e1071','1.6-8')
install.versions('foreach','1.4.4')
install.versions('ggplot2','3.1.0')
install.versions('ini','0.3.1')
install.versions('jsonlite','1.5')
install.versions('lubridate','1.7.4')
install.versions('plyr','1.8.4')
install.versions('quantmod','0.4-11')
install.versions('randomForest','4.6-12')
install.versions('Rcpp','0.12.17')
install.versions('DT','0.2')
install.versions('RCurl','1.95-4.8')
install.versions('reshape2','1.4.3')
install.versions('rpart','4.1-10')
install.versions('RPostgreSQL','0.4-1')
install.versions('RPostgres','1.1.1')
install.versions('rPython', '0.0-6')
install.versions('stringi','1.2.4')
install.versions('stringr','1.2.0')
install.versions('tibble','1.3.4')
install.versions('tidyr','0.7.2')
install.versions('timeDate','3042.101')
install.versions('XML','3.98-1.16')
install.versions('xts','0.10-0')
install.versions('zoo','1.8-0')

# new DV packages
install.versions('base64enc', '0.1-3')
install.versions('digest', '0.6.15')
install.versions('httr', '1.3.1')
install.versions('openxlsx', '4.1.0')
install.versions('R.utils', '2.7.0')
install.versions('reshape', '0.8.8')
install.versions('urltools', '1.7.0')
install.versions('xml2', '1.2.0')
install.versions('ini', '0.3.1')
install.versions('rlang', '0.2.1')
install.versions('gridExtra', '2.3')
